spring.application.name=Text-to-Learn

# postgresql configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/texttolearn
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

#AI API Config
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openrouter.baseurl=https://openrouter.ai/api/v1
spring.ai.openrouter.model-name=openai/gpt-oss-120b:free