package com.example.backend.Text.to.Learn.entities;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

/**
 * JPA entity representing a {@code Course} record in the {@code course} database table.
 *
 * <p>A course is the top-level container in the content hierarchy:
 * <pre>Course → Module → Lesson</pre>
 *
 * <p>The {@code modules} field maintains a bidirectional one-to-many relationship
 * with {@link ModuleEntity}. Cascade operations ensure that saving or deleting a
 * course automatically propagates to its child modules (and their lessons).
 *
 * <p>Lombok annotations:
 * <ul>
 *   <li>{@code @Data}            — generates getters, setters, equals, hashCode, toString</li>
 *   <li>{@code @Builder}         — enables builder-pattern construction</li>
 *   <li>{@code @NoArgsConstructor} / {@code @AllArgsConstructor} — required by JPA and Jackson</li>
 * </ul>
 */
@Entity                     // marks this class as a JPA-managed entity (maps to a DB table)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "course")     // explicitly names the table "course" in the database
public class CourseEntity {

    /** Auto-incremented primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Display name of the course (e.g., "Introduction to Java"). */
    private String title;

    /**
     * Short description of the course contents.
     * Stored as a VARCHAR(2000) column to accommodate longer summaries.
     */
    @Column(length = 2000)
    private String description;

    /**
     * Ordered list of modules that belong to this course.
     *
     * <p>Relationship details:
     * <ul>
     *   <li>{@code mappedBy = "courseEntity"} — the foreign key is managed by {@link ModuleEntity#courseEntity}</li>
     *   <li>{@code cascade = ALL}             — all JPA operations propagate to child modules</li>
     *   <li>{@code orphanRemoval = true}      — modules not referenced by any course are auto-deleted</li>
     * </ul>
     *
     * <p>{@code @JsonManagedReference} prevents infinite recursion during JSON serialization
     * (pairs with {@code @JsonBackReference} on {@link ModuleEntity}).
     */
    @OneToMany(mappedBy = "courseEntity", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference       // "forward" side of the bidirectional JSON reference
    @Builder.Default            // required so the Builder sets the default value (empty list)
    private List<ModuleEntity> modules = new ArrayList<>();
}