package com.example.backend.Text.to.Learn.entities;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Represents an anonymous guest browsing session.
 * The UUID {@code id} is stored in an HttpOnly {@code GUEST_SESSION_ID} cookie.
 * After 7 days the session (and its courses) are deleted by the scheduled cleanup job.
 */
@Entity
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "guest_sessions")
public class GuestSessionEntity {

    /** UUID string set by the application (not auto-generated by DB). */
    @Id
    private String id;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Courses belonging to this guest will be deleted after this timestamp. */
    @Column(nullable = false)
    private LocalDateTime expiresAt;

    @PrePersist
    protected void prePersist() {
        this.createdAt = LocalDateTime.now();
        if (this.expiresAt == null) {
            this.expiresAt = this.createdAt.plusDays(7);
        }
    }
}
