package com.example.backend.Text.to.Learn.entities;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import lombok.*;

/**
 * JPA entity representing a {@code Lesson} record in the {@code lesson} database table.
 *
 * <p>A lesson is the leaf-level content node in the course hierarchy:
 * <pre>Course → Module → Lesson</pre>
 *
 * <p>Each lesson belongs to exactly one {@link ModuleEntity} (many-to-one) and
 * holds the actual educational content plus an optional supplementary YouTube video URL.
 *
 * <p>Lombok annotations:
 * <ul>
 *   <li>{@code @Data}              — generates getters, setters, equals, hashCode, toString</li>
 *   <li>{@code @Builder}           — enables builder-pattern construction</li>
 *   <li>{@code @ToString(exclude)} — prevents {@code moduleEntity} from being traversed in toString
 *                                    to avoid circular reference stack overflows</li>
 * </ul>
 */
@Entity                             // marks this class as a JPA-managed entity (maps to a DB table)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "lesson")             // explicitly names the table "lesson" in the database
@ToString(exclude = "moduleEntity") // excludes parent reference from toString to prevent circular calls
public class LessonEntity {

    /** Auto-incremented primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Display name of the lesson (e.g., "Variables and Data Types"). */
    private String title;

    /**
     * Main educational content of the lesson.
     * Stored as a {@code TEXT} column (unlimited length) to support long articles.
     */
    @Column(columnDefinition = "TEXT")
    private String content;

    /**
     * The parent module that this lesson belongs to.
     *
     * <p>Relationship details:
     * <ul>
     *   <li>{@code FetchType.LAZY} — the parent module is not loaded until explicitly accessed</li>
     *   <li>{@code module_id}      — the foreign key column in the {@code lesson} table</li>
     * </ul>
     *
     * <p>{@code @JsonBackReference} suppresses serialization of this field to prevent
     * circular JSON output (paired with {@code @JsonManagedReference} on {@link ModuleEntity}).
     */
    @ManyToOne(fetch = FetchType.LAZY)  // many lessons → one module
    @JoinColumn(name = "module_id")     // foreign key column in the DB
    @JsonBackReference                  // "back" side — suppressed during JSON serialization
    private ModuleEntity moduleEntity;

    /**
     * Resolved YouTube video URL for this lesson (e.g., "https://www.youtube.com/watch?v=...").
     * Fetched from the YouTube Data API via {@link com.example.backend.Text.to.Learn.services.YoutubeService}.
     * May be {@code null} if no video was found or the YouTube lookup was skipped.
     */
    private String YoutubeUrl;

    /**
     * Whether the learner has marked this lesson as completed.
     *
     * <p>Persisted in the {@code lesson} table so progress survives browser
     * clears and cross-device sessions. Defaults to {@code false}.</p>
     */
    @Column(nullable = false)
    @Builder.Default
    private boolean completed = false;
}