package com.example.backend.Text.to.Learn.entities;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

/**
 * JPA entity representing a {@code Module} record in the {@code module} database table.
 *
 * <p>A module is the mid-level grouping node in the content hierarchy:
 * <pre>Course → Module → Lesson</pre>
 *
 * <p>Each module belongs to exactly one {@link CourseEntity} (many-to-one) and
 * contains an ordered list of {@link LessonEntity} objects (one-to-many).
 *
 * <p>Lombok annotations:
 * <ul>
 *   <li>{@code @Data}              — generates getters, setters, equals, hashCode, toString</li>
 *   <li>{@code @Builder}           — enables builder-pattern construction</li>
 *   <li>{@code @ToString(exclude)} — prevents {@code courseEntity} from being traversed in toString
 *                                    to avoid circular reference stack overflows</li>
 * </ul>
 */
@Entity                         // marks this class as a JPA-managed entity (maps to a DB table)
@Data
@Builder                        // provides builder pattern for object creation
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "module")         // explicitly names the table "module" in the database
@ToString(exclude = "courseEntity") // excludes parent reference from toString to avoid circular calls
public class ModuleEntity {

    /** Auto-incremented primary key generated by the database. */
    @Id                                                         // marks as primary key of the table
    @GeneratedValue(strategy = GenerationType.IDENTITY)        // auto-increments the id value
    private Long id;

    /** Display name of the module (e.g., "Getting Started with Java"). */
    private String title;

    /**
     * The parent course that this module belongs to.
     *
     * <p>Relationship details:
     * <ul>
     *   <li>{@code FetchType.LAZY}  — the parent course is not loaded until explicitly accessed</li>
     *   <li>{@code course_id}       — the foreign key column in the {@code module} table</li>
     *   <li>{@code nullable = false} — every module must belong to a course</li>
     * </ul>
     *
     * <p>{@code @JsonBackReference} suppresses serialization of this field to prevent
     * circular JSON output (paired with {@code @JsonManagedReference} on {@link CourseEntity}).
     */
    @ManyToOne(fetch = FetchType.LAZY)                         // many modules → one course
    @JoinColumn(name = "course_id", nullable = false)          // foreign key column in the DB
    @JsonBackReference                                          // "back" side — suppressed during JSON serialization
    private CourseEntity courseEntity;

    /**
     * Ordered list of lessons that belong to this module.
     *
     * <p>Relationship details:
     * <ul>
     *   <li>{@code mappedBy = "moduleEntity"} — foreign key is managed by {@link LessonEntity#moduleEntity}</li>
     *   <li>{@code cascade = ALL}             — all JPA operations propagate to child lessons</li>
     *   <li>{@code orphanRemoval = true}      — lessons not referenced by any module are auto-deleted</li>
     * </ul>
     */
    @OneToMany(mappedBy = "moduleEntity", cascade = CascadeType.ALL, orphanRemoval = true) // one module → many lessons
    @JsonManagedReference       // "forward" side of the bidirectional JSON reference
    @Builder.Default            // required so the Builder initialises to an empty list
    private List<LessonEntity> lessons = new ArrayList<>();
}