package com.example.backend.Text.to.Learn.entities;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * JPA entity representing a registered user in the {@code users} database table.
 *
 * <p>Stores credentials with a BCrypt-hashed password — the raw password is never persisted.
 * The {@code createdAt} timestamp is set automatically on first insert via {@link #prePersist()}.
 *
 * <p>A user owns zero or more {@link CourseEntity} objects (one-to-many).
 */
@Entity
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "users")
public class UserEntity {

    /** Auto-incremented primary key. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Full display name of the user. */
    @Column(nullable = false)
    private String name;

    /** Unique email address — used as the login identifier. */
    @Column(unique = true, nullable = false)
    private String email;

    /** BCrypt hash of the user's password. The raw password is never stored. */
    @Column(nullable = false)
    private String passwordHash;

    /** Timestamp of account creation. Set once on insert, never updated. */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Courses generated by this user. Deleting a user cascades to their courses. */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<CourseEntity> courses = new ArrayList<>();

    /** Automatically sets {@code createdAt} to the current UTC time before the first DB insert. */
    @PrePersist
    protected void prePersist() {
        this.createdAt = LocalDateTime.now();
    }
}
